# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('isbn', models.PositiveIntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
